-- ============================================================================
-- PROJETO: CONFERÊNCIA DE DIÁRIA E PASSAGENS AÉREAS DE MOBILIZADOS
-- PADRÃO: Metodologia de Padrões e Nomenclaturas de Banco de Dados MJSP v1.3
-- COMPATIBILIDADE: Oracle Database 19c/21c/23ai / Oracle APEX 24.2+
-- ============================================================================

PROMPT ===================================================
PROMPT CRIANDO SEQUENCES SEGUNDO PADRÃO MJSP (SEQ_<TABELA>)
PROMPT ===================================================

CREATE SEQUENCE SEQ_CONFERENCIA_VIAGEM START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_CONFERENCIA_FONTE START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_CONFERENCIA_ITEM START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_CONFERENCIA_EVIDENCIA START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_AUDITORIA_CONFERENCIA START WITH 1 INCREMENT BY 1 NOCACHE;

PROMPT ===================================================
PROMPT CRIANDO TABELAS DO SISTEMA DE CONFERÊNCIA
PROMPT ===================================================

-- 1. Tabela Master de Sessão/Lote de Conferência
CREATE TABLE TB_CONFERENCIA_VIAGEM (
    CO_CONFERENCIA          NUMBER(10)          NOT NULL,
    NO_CONFERENCIA          VARCHAR2(100)       NOT NULL,
    DS_PROCESSO_SEI         VARCHAR2(30),
    DH_CRIACAO              TIMESTAMP           DEFAULT SYSTIMESTAMP NOT NULL,
    DH_FINALIZACAO          TIMESTAMP,
    ST_CONFERENCIA          VARCHAR2(30)        DEFAULT 'EM_ANDAMENTO' NOT NULL,
    NO_USUARIO_CRIACAO      VARCHAR2(100)       NOT NULL,
    QT_TOTAL_ITENS          NUMBER(6)           DEFAULT 0 NOT NULL,
    QT_CONFERIDO_OK         NUMBER(6)           DEFAULT 0 NOT NULL,
    QT_DIVERGENCIA          NUMBER(6)           DEFAULT 0 NOT NULL,
    QT_REQUER_REVISAO       NUMBER(6)           DEFAULT 0 NOT NULL,
    DS_OBSERVACOES          VARCHAR2(4000),
    CONSTRAINT PK_CONFERENCIA_VIAGEM_CO PRIMARY KEY (CO_CONFERENCIA),
    CONSTRAINT CK_CONF_VIAGEM_ST CHECK (ST_CONFERENCIA IN ('EM_ANDAMENTO', 'CONCLUIDA', 'CANCELADA'))
);

COMMENT ON TABLE TB_CONFERENCIA_VIAGEM IS 'Sessão ou lote de auditoria/conferência de viagens e passagens aéreas';
COMMENT ON COLUMN TB_CONFERENCIA_VIAGEM.CO_CONFERENCIA IS 'Identificador sequencial único da conferência';
COMMENT ON COLUMN TB_CONFERENCIA_VIAGEM.NO_CONFERENCIA IS 'Título descritivo da conferência ou evento';
COMMENT ON COLUMN TB_CONFERENCIA_VIAGEM.DS_PROCESSO_SEI IS 'Número do Processo SEI de referência (ex: 08020.008848/2026-06)';
COMMENT ON COLUMN TB_CONFERENCIA_VIAGEM.ST_CONFERENCIA IS 'Status global da conferência: EM_ANDAMENTO, CONCLUIDA, CANCELADA';

-- 2. Tabela de Fontes Documentais Carregadas na Conferência
CREATE TABLE TB_CONFERENCIA_FONTE (
    CO_FONTE                NUMBER(10)          NOT NULL,
    CO_CONFERENCIA          NUMBER(10)          NOT NULL,
    TP_FONTE                VARCHAR2(20)        NOT NULL,
    NO_ARQUIVO              VARCHAR2(255)       NOT NULL,
    DS_ORIGEM               VARCHAR2(500),
    NU_TAMANHO_BYTES        NUMBER(14),
    DS_MIME_TYPE            VARCHAR2(100),
    QT_REGISTROS_LIDOS      NUMBER(6)           DEFAULT 0 NOT NULL,
    ST_PROCESSAMENTO        VARCHAR2(35)        DEFAULT 'PROCESSADO' NOT NULL,
    DS_LOG_ERROS            VARCHAR2(4000),
    DH_CARGA                TIMESTAMP           DEFAULT SYSTIMESTAMP NOT NULL,
    NO_USUARIO_CARGA        VARCHAR2(100)       NOT NULL,
    CONSTRAINT PK_CONFERENCIA_FONTE_CO PRIMARY KEY (CO_FONTE),
    CONSTRAINT FK_CONF_VIAGEM_FONTE FOREIGN KEY (CO_CONFERENCIA) 
        REFERENCES TB_CONFERENCIA_VIAGEM (CO_CONFERENCIA) ON DELETE CASCADE,
    CONSTRAINT CK_CONF_FONTE_TP CHECK (TP_FONTE IN ('BANCO', 'PLANILHA', 'PDF')),
    CONSTRAINT CK_CONF_FONTE_ST CHECK (ST_PROCESSAMENTO IN ('PROCESSADO', 'PROCESSADO_COM_AVISOS', 'ERRO_PROCESSAMENTO', 'ARQUIVO_INVALIDO'))
);

COMMENT ON TABLE TB_CONFERENCIA_FONTE IS 'Registro das fontes de dados importadas para conferência (Banco, CSV/XLSX, PDFs)';
COMMENT ON COLUMN TB_CONFERENCIA_FONTE.TP_FONTE IS 'Tipo de fonte: BANCO, PLANILHA, PDF';

-- 3. Tabela de Itens Comparados (Viajantes e Trechos)
CREATE TABLE TB_CONFERENCIA_ITEM (
    CO_ITEM                 NUMBER(10)          NOT NULL,
    CO_CONFERENCIA          NUMBER(10)          NOT NULL,
    NO_PASSAGEIRO_ORIG      VARCHAR2(150)       NOT NULL,
    NO_PASSAGEIRO_NORM      VARCHAR2(150)       NOT NULL,
    NU_CPF_ORIG             VARCHAR2(20),
    NU_CPF_MASC             VARCHAR2(20),
    NU_DOCUMENTO_OUTRO      VARCHAR2(50),
    SG_COMPANHIA            VARCHAR2(30),
    CD_LOCALIZADOR          VARCHAR2(30),
    NU_BILHETE              VARCHAR2(40),
    DS_ORIGEM_IDA           VARCHAR2(100),
    DS_DESTINO_IDA          VARCHAR2(100),
    DT_IDA                  DATE,
    HR_PARTIDA_IDA          VARCHAR2(10),
    HR_CHEGADA_IDA          VARCHAR2(10),
    DS_ORIGEM_VOLTA         VARCHAR2(100),
    DS_DESTINO_VOLTA        VARCHAR2(100),
    DT_VOLTA                DATE,
    HR_PARTIDA_VOLTA        VARCHAR2(10),
    HR_CHEGADA_VOLTA        VARCHAR2(10),
    VL_TOTAL                NUMBER(12,2),
    ST_CONFERENCIA_ITEM     VARCHAR2(35)        DEFAULT 'REQUER_REVISAO' NOT NULL,
    PC_SIMILARIDADE_NOME    NUMBER(5,2),
    DS_MOTIVO_SITUACAO      VARCHAR2(4000),
    IC_REVISADO_HUMANO      CHAR(1)             DEFAULT 'N' NOT NULL,
    NO_USUARIO_REVISOR      VARCHAR2(100),
    DH_REVISAO_HUMANA       TIMESTAMP,
    DS_JUSTIFICATIVA_REVISAO VARCHAR2(4000),
    ST_DECISAO_HUMANA       VARCHAR2(50),
    CONSTRAINT PK_CONFERENCIA_ITEM_CO PRIMARY KEY (CO_ITEM),
    CONSTRAINT FK_CONF_VIAGEM_ITEM FOREIGN KEY (CO_CONFERENCIA) 
        REFERENCES TB_CONFERENCIA_VIAGEM (CO_CONFERENCIA) ON DELETE CASCADE,
    CONSTRAINT CK_CONF_ITEM_ST CHECK (ST_CONFERENCIA_ITEM IN (
        'CONFERIDO_SEM_DIVERGENCIA',
        'DIVERGENCIA',
        'DADO_AUSENTE',
        'CORRESPONDENCIA_AMBIGUA',
        'REQUER_REVISAO',
        'ARQUIVO_NAO_PROCESSADO'
    )),
    CONSTRAINT CK_CONF_ITEM_REVISADO CHECK (IC_REVISADO_HUMANO IN ('S','N')),
    CONSTRAINT CK_CONF_ITEM_DECISAO CHECK (ST_DECISAO_HUMANA IS NULL OR ST_DECISAO_HUMANA IN ('APROVADO_REVISOR', 'REJEITADO_REVISOR', 'SOLICITADA_COMPLEMENTACAO'))
);

COMMENT ON TABLE TB_CONFERENCIA_ITEM IS 'Resultado detalhado da conferência por passageiro / emissão';
COMMENT ON COLUMN TB_CONFERENCIA_ITEM.ST_CONFERENCIA_ITEM IS 'Status determinístico de conferência (6 estados padronizados)';
COMMENT ON COLUMN TB_CONFERENCIA_ITEM.NU_CPF_MASC IS 'CPF com máscara para preservação de privacidade (LGPD)';
COMMENT ON COLUMN TB_CONFERENCIA_ITEM.IC_REVISADO_HUMANO IS 'Flag S/N indicando se houve autorização/revisão explícita de um operador';

-- 4. Tabela de Evidências Campo a Campo
CREATE TABLE TB_CONFERENCIA_EVIDENCIA (
    CO_EVIDENCIA            NUMBER(10)          NOT NULL,
    CO_ITEM                 NUMBER(10)          NOT NULL,
    NM_CAMPO                VARCHAR2(50)        NOT NULL,
    VL_FONTE_BANCO          VARCHAR2(300),
    VL_FONTE_PLANILHA       VARCHAR2(300),
    VL_FONTE_PDF            VARCHAR2(300),
    DS_REF_BANCO            VARCHAR2(200),
    DS_REF_PLANILHA         VARCHAR2(200),
    DS_REF_PDF              VARCHAR2(200),
    NU_PAGINA_PDF           NUMBER(4),
    DS_TRECHO_PDF           VARCHAR2(1000),
    IC_OCR                  CHAR(1)             DEFAULT 'N' NOT NULL,
    ST_DIVERGENCIA_CAMPO    VARCHAR2(30)        NOT NULL,
    DS_OBSERVACAO           VARCHAR2(1000),
    CONSTRAINT PK_CONFERENCIA_EVIDENCIA_CO PRIMARY KEY (CO_EVIDENCIA),
    CONSTRAINT FK_CONF_ITEM_EVIDENCIA FOREIGN KEY (CO_ITEM) 
        REFERENCES TB_CONFERENCIA_ITEM (CO_ITEM) ON DELETE CASCADE,
    CONSTRAINT CK_CONF_EVID_OCR CHECK (IC_OCR IN ('S','N')),
    CONSTRAINT CK_CONF_EVID_ST CHECK (ST_DIVERGENCIA_CAMPO IN ('CONFORME', 'DIVERGENCIA', 'AUSENTE', 'REQUER_VERIFICACAO'))
);

COMMENT ON TABLE TB_CONFERENCIA_EVIDENCIA IS 'Trilha de evidências de valores de cada campo entre as fontes comparadas';
COMMENT ON COLUMN TB_CONFERENCIA_EVIDENCIA.IC_OCR IS 'Indica se a extração do PDF decorreu de OCR (menor confiabilidade)';

-- 5. Tabela de Auditoria e Decisões Humanas (Rastreabilidade e Segurança)
CREATE TABLE TB_AUDITORIA_CONFERENCIA (
    CO_AUDITORIA            NUMBER(10)          NOT NULL,
    CO_CONFERENCIA          NUMBER(10)          NOT NULL,
    CO_ITEM                 NUMBER(10),
    DH_REGISTRO             TIMESTAMP           DEFAULT SYSTIMESTAMP NOT NULL,
    NO_USUARIO              VARCHAR2(100)       NOT NULL,
    TP_ACAO                 VARCHAR2(50)        NOT NULL,
    DS_JUSTIFICATIVA        VARCHAR2(4000)      NOT NULL,
    DS_DADOS_ANTERIORES     VARCHAR2(4000),
    DS_DADOS_NOVOS          VARCHAR2(4000),
    DS_IP_CLIENTE           VARCHAR2(50),
    CONSTRAINT PK_AUDITORIA_CONF_CO PRIMARY KEY (CO_AUDITORIA),
    CONSTRAINT FK_CONF_VIAGEM_AUDITORIA FOREIGN KEY (CO_CONFERENCIA) 
        REFERENCES TB_CONFERENCIA_VIAGEM (CO_CONFERENCIA) ON DELETE CASCADE
);

COMMENT ON TABLE TB_AUDITORIA_CONFERENCIA IS 'Log imutável de ações e deliberações humanas sobre os registros de conferência';

-- Triggers para preenchimento de Primary Keys via Sequence
CREATE OR REPLACE TRIGGER TG_CONFERENCIA_VIAGEM_I
BEFORE INSERT ON TB_CONFERENCIA_VIAGEM
FOR EACH ROW
BEGIN
    IF :NEW.CO_CONFERENCIA IS NULL THEN
        :NEW.CO_CONFERENCIA := SEQ_CONFERENCIA_VIAGEM.NEXTVAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TG_CONFERENCIA_FONTE_I
BEFORE INSERT ON TB_CONFERENCIA_FONTE
FOR EACH ROW
BEGIN
    IF :NEW.CO_FONTE IS NULL THEN
        :NEW.CO_FONTE := SEQ_CONFERENCIA_FONTE.NEXTVAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TG_CONFERENCIA_ITEM_I
BEFORE INSERT ON TB_CONFERENCIA_ITEM
FOR EACH ROW
BEGIN
    IF :NEW.CO_ITEM IS NULL THEN
        :NEW.CO_ITEM := SEQ_CONFERENCIA_ITEM.NEXTVAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TG_CONFERENCIA_EVIDENCIA_I
BEFORE INSERT ON TB_CONFERENCIA_EVIDENCIA
FOR EACH ROW
BEGIN
    IF :NEW.CO_EVIDENCIA IS NULL THEN
        :NEW.CO_EVIDENCIA := SEQ_CONFERENCIA_EVIDENCIA.NEXTVAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TG_AUDITORIA_CONFERENCIA_I
BEFORE INSERT ON TB_AUDITORIA_CONFERENCIA
FOR EACH ROW
BEGIN
    IF :NEW.CO_AUDITORIA IS NULL THEN
        :NEW.CO_AUDITORIA := SEQ_AUDITORIA_CONFERENCIA.NEXTVAL;
    END IF;
END;
/

